import os

from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]
SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_KEY"]
TELEGRAM_BOT_TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
TELEGRAM_CHANNEL_ID = os.environ["TELEGRAM_CHANNEL_ID"]
FINNHUB_API_KEY = os.environ.get("FINNHUB_API_KEY", "")

CIRCUIT_BREAKER_THRESHOLD = 20
DEFAULT_DAILY_DROP_THRESHOLD = 5.0
DEFAULT_LOOKBACK_PERIOD = 20
DEFAULT_DROP_THRESHOLD = 10.0
